import {
  // category icons
  PenLine,
  Image,
  Code,
  Zap,
  Clapperboard,
  AudioLines,
  BookOpen,
  Megaphone,
  // feature icons (from seed data)
  Fingerprint,
  LayoutTemplate,
  Workflow,
  Database,
  Recycle,
  BookMarked,
  Sparkles,
  Wand2,
  Globe,
  Gauge,
  Palette,
  Users,
  Frame,
  Target,
  MessagesSquare,
  Type,
  Lock,
  SlidersHorizontal,
  Cog,
  PaintBucket,
  ShieldCheck,
  Layers,
  TextCursorInput,
  MessageSquareCode,
  Bot,
  Keyboard,
  Waves,
  TerminalSquare,
  Rocket,
  Cloud,
  Table,
  Search,
  Network,
  CalendarClock,
  KanbanSquare,
  CalendarPlus,
  Brush,
  Scissors,
  Play,
  UserRound,
  Languages,
  FileVideo,
  Mic,
  Music,
  Quote,
  Telescope,
  FolderKanban,
  ClipboardList,
  FileText,
  Microscope,
  ChartBar,
  TrendingUp,
  Camera,
  Images,
  AudioWaveform,
  // UI / chrome icons
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  Star,
  Menu,
  X,
  Sun,
  Moon,
  Command,
  ExternalLink,
  Check,
  ChevronRight,
  ChevronDown,
  Filter,
  Eye,
  Scale,
  Building2,
  Calendar,
  Tag,
  ThumbsUp,
  BadgeCheck,
  CircleCheck,
  CircleX,
  Plus,
  Minus,
  LayoutGrid,
  List,
  Sprout,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * Icon registry. Seed data stores Lucide icon names as *strings*; this maps
 * them to imported components so a `lucide-react` rename only needs a fix in
 * one place (and we only bundle the icons we actually use). Unknown names fall
 * back to a neutral glyph instead of crashing.
 */
const registry = {
  PenLine,
  Image,
  Code,
  Zap,
  Clapperboard,
  AudioLines,
  BookOpen,
  Megaphone,
  Fingerprint,
  LayoutTemplate,
  Workflow,
  Database,
  Recycle,
  BookMarked,
  Sparkles,
  Wand2,
  Globe,
  Gauge,
  Palette,
  Users,
  Frame,
  Target,
  MessagesSquare,
  Type,
  Lock,
  SlidersHorizontal,
  Cog,
  PaintBucket,
  ShieldCheck,
  Layers,
  TextCursorInput,
  MessageSquareCode,
  Bot,
  Keyboard,
  Waves,
  TerminalSquare,
  Rocket,
  Cloud,
  Table,
  Search,
  Network,
  CalendarClock,
  KanbanSquare,
  CalendarPlus,
  Brush,
  Scissors,
  Play,
  UserRound,
  Languages,
  FileVideo,
  Mic,
  Music,
  Quote,
  Telescope,
  FolderKanban,
  ClipboardList,
  FileText,
  Microscope,
  ChartBar,
  TrendingUp,
  Camera,
  Images,
  AudioWaveform,
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  Star,
  Menu,
  X,
  Sun,
  Moon,
  Command,
  ExternalLink,
  Check,
  ChevronRight,
  ChevronDown,
  Filter,
  Eye,
  Scale,
  Building2,
  Calendar,
  Tag,
  ThumbsUp,
  BadgeCheck,
  CircleCheck,
  CircleX,
  Plus,
  Minus,
  LayoutGrid,
  List,
  Sprout,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof registry;

export function Icon({
  name,
  className,
  ...props
}: {
  name: string;
  className?: string;
} & React.ComponentProps<LucideIcon>) {
  const Glyph = registry[name as IconName] ?? Sparkles;
  if (process.env.NODE_ENV !== "production" && !(name in registry)) {
    console.warn(`[Enki] Unknown icon "${name}" — add it to the icon registry.`);
  }
  return <Glyph className={cn("size-4", className)} {...props} />;
}
